### ISSUE TITLE
grant_type and scope in URL query 

### ISSUE THREAD

**Issue by mkyrychenko** [foobert/jwtdummy#2]
If subj requested in URL query as figured
`http://jwt-auth:3000/token?grant_type=client_credentials&scope=openid`
instead of issuing of openId, it signs a request and client fails with an error.

https://github.com/foobert/jwtdummy/blob/0faa1b68de1d2205276c726d264eaa52e74acdc1/lib/openid.js#L5

The `req`-check should be extended
`let grantType = req.query.grant_type || req.body.grant_type;` and 
`let scope = req.query.scope || req.body.scope;` accordingly.

At the end it looks like
`if (grantType !== "client_credentials" || ...` 

PR https://github.com/foobert/jwtdummy/pull/3 is created

**Comment by foobert** [comment]
Fixed
